### ISSUE TITLE
*line Expiry Times

### ISSUE THREAD

**Issue by SketchNI** [unrealircd/unrealircd-webpanel-laravel#3]
Expiry times for g/z/gz/k-lines are always permanent which should not be the case if a date and time is provided in the web panel.

**Comment by ValwareIRC** [comment]
Just a nudge in case you're still out there =]
This issue has been fixed as of https://github.com/unrealircd/unrealircd/commit/b5c86981fab27478cce32d8a3815520891896452
Hope you're well
